# Generated by Django 4.1.7 on 2023-04-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantDRF', '0005_rename_applicantprofile_application_applicant_profile'),
        ('employerDRF', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostJobs',
            new_name='Jobs',
        ),
    ]
