# Generated by Django 4.1.7 on 2023-05-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employerDRF', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='slug',
            field=models.SlugField(),
        ),
    ]
