# Generated by Django 4.1.7 on 2023-04-22 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('contact_phone', models.PositiveIntegerField(null=True)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('education', models.CharField(max_length=500)),
                ('certification', models.ImageField(blank=True, null=True, upload_to='images/certificates')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/users')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='images/files')),
                ('cv', models.FileField(blank=True, null=True, upload_to='images/files')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=255)),
            ],
        ),
    ]
