# Generated by Django 4.1.7 on 2023-05-17 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employerDRF', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('applicantDRF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerDRF.jobs'),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
