# Generated by Django 4.1.7 on 2023-04-22 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employerDRF', '0001_initial'),
        ('applicantDRF', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='job',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ApplicantProfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicantDRF.applicantprofile')),
                ('jobs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employerDRF.postjobs')),
            ],
        ),
    ]
