# Generated by Django 4.1.7 on 2023-04-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantDRF', '0003_remove_applicantprofile_job_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='skills',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='skills',
            field=models.CharField(default='fff', max_length=255),
            preserve_default=False,
        ),
    ]
