# Generated by Django 4.1.7 on 2023-04-22 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantDRF', '0004_remove_applicantprofile_skills_delete_skill_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='ApplicantProfile',
            new_name='applicant_profile',
        ),
    ]
